"""added is_goose column to images table

Revision ID: 328460e2a637
Revises: 9f812359ea64
Create Date: 2018-08-26 15:37:24.394481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328460e2a637'
down_revision = '9f812359ea64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_goose', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'is_goose')
    # ### end Alembic commands ###
