"""added url Column to images

Revision ID: 479f879ed436
Revises: 87d593ee4696
Create Date: 2018-07-31 03:15:04.661957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479f879ed436'
down_revision = '87d593ee4696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.String(), nullable=False))
    op.create_unique_constraint(op.f('uq_images_url'), 'images', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_images_url'), 'images', type_='unique')
    op.drop_column('images', 'url')
    # ### end Alembic commands ###
