"""added relationship between images and tasks 

Revision ID: 9f812359ea64
Revises: 479f879ed436
Create Date: 2018-08-26 14:10:20.428279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f812359ea64'
down_revision = '479f879ed436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_tasks_image_id_images'), 'tasks', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_image_id_images'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'image_id')
    # ### end Alembic commands ###
