"""added images table

Revision ID: d88ec284fa6d
Revises: 
Create Date: 2018-07-17 19:05:50.815260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88ec284fa6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
            'images',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('file_name', sa.String(), nullable=False),
            sa.PrimaryKeyConstraint('id')
            )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
